var Presets = {
    nations: ["england", "northern ireland", "scotland", "wales"],
    regions: [
        "east midlands",
        "east of england",
        "london",
        "north east",
        "north west",
        "south east",
        "south west",
        "west midlands",
        "yorkshire and the humber",
    ],
    colours: [
        "#D10046",
        "#428BCA",
        "#F0AD4E",
        "#69D100",
        "#D695BE",
        "#7F8C8D",
        "#8E44AD",
        "#AD4363",
        "#D1D100",
        "#AD8D43",
    ],
    initialFeed: ["Newcastle-under-Lyme", "Staffordshire"],
};
